tee_append copy seek_io : ../lib/error_functions.o

../lib/error_functions.o : ../lib/error_functions.c

.PHONY : clean
clean :
	rm -f copy
	rm -f seek_io
	rm -f tee_append
	rm -f ../lib/error_functions.o
